---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.2
    hooks:
      - id: terraform_fmt

  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        language: system
        entry: bash -c 'cd app && gofmt -s -w .'
        pass_filenames: false
        types: [go]

      - id: golangci-lint
        name: go lint
        language: system
        entry: bash -c 'cd app/ocost && golangci-lint run'
        pass_filenames: false
        types: [go]

      - id: go-test
        name: go test
        language: system
        entry: bash -c 'cd app/ocost/cmd && go test -v'
        pass_filenames: false
        types: [go]
