---
name: "Integration test"

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          cd app
          make test-and-exit
